/** Guest-post / blogging niches for vendor tagging (slug must stay stable after first seed). */
export const SEED_NICHES: { slug: string; label: string; sortOrder: number }[] = [
  { slug: "general", label: "General", sortOrder: 0 },
  { slug: "tech", label: "Technology", sortOrder: 1 },
  { slug: "saas", label: "SaaS & Software", sortOrder: 2 },
  { slug: "marketing", label: "Marketing", sortOrder: 3 },
  { slug: "seo", label: "SEO", sortOrder: 4 },
  { slug: "content-marketing", label: "Content marketing", sortOrder: 5 },
  { slug: "social-media", label: "Social media", sortOrder: 6 },
  { slug: "email-marketing", label: "Email marketing", sortOrder: 7 },
  { slug: "affiliate-marketing", label: "Affiliate marketing", sortOrder: 8 },
  { slug: "blogging", label: "Blogging", sortOrder: 9 },
  { slug: "wordpress", label: "WordPress", sortOrder: 10 },
  { slug: "web-design", label: "Web design", sortOrder: 11 },
  { slug: "web-development", label: "Web development", sortOrder: 12 },
  { slug: "cybersecurity", label: "Cybersecurity", sortOrder: 13 },
  { slug: "ai-ml", label: "AI & machine learning", sortOrder: 14 },
  { slug: "health", label: "Health & wellness", sortOrder: 15 },
  { slug: "fitness", label: "Fitness", sortOrder: 16 },
  { slug: "nutrition", label: "Nutrition", sortOrder: 17 },
  { slug: "weight-loss", label: "Weight loss", sortOrder: 18 },
  { slug: "mental-health", label: "Mental health", sortOrder: 19 },
  { slug: "finance", label: "Personal finance", sortOrder: 20 },
  { slug: "investing", label: "Investing", sortOrder: 21 },
  { slug: "crypto", label: "Crypto & Web3", sortOrder: 22 },
  { slug: "real-estate", label: "Real estate", sortOrder: 23 },
  { slug: "insurance", label: "Insurance", sortOrder: 24 },
  { slug: "travel", label: "Travel", sortOrder: 25 },
  { slug: "food", label: "Food & recipes", sortOrder: 26 },
  { slug: "lifestyle", label: "Lifestyle", sortOrder: 27 },
  { slug: "fashion", label: "Fashion & beauty", sortOrder: 28 },
  { slug: "home", label: "Home & garden", sortOrder: 29 },
  { slug: "home-improvement", label: "Home improvement", sortOrder: 30 },
  { slug: "diy", label: "DIY & crafts", sortOrder: 31 },
  { slug: "interior-design", label: "Interior design", sortOrder: 32 },
  { slug: "architecture", label: "Architecture", sortOrder: 33 },
  { slug: "gardening", label: "Gardening", sortOrder: 34 },
  { slug: "parenting", label: "Parenting", sortOrder: 35 },
  { slug: "mom-blog", label: "Mom blog", sortOrder: 36 },
  { slug: "pregnancy", label: "Pregnancy & baby", sortOrder: 37 },
  { slug: "education", label: "Education", sortOrder: 38 },
  { slug: "career", label: "Career & jobs", sortOrder: 39 },
  { slug: "remote-work", label: "Remote work", sortOrder: 40 },
  { slug: "productivity", label: "Productivity", sortOrder: 41 },
  { slug: "self-improvement", label: "Self improvement", sortOrder: 42 },
  { slug: "pets", label: "Pets & animals", sortOrder: 43 },
  { slug: "sports", label: "Sports", sortOrder: 44 },
  { slug: "gaming", label: "Gaming", sortOrder: 45 },
  { slug: "entertainment", label: "Entertainment", sortOrder: 46 },
  { slug: "movies", label: "Movies & TV", sortOrder: 47 },
  { slug: "music", label: "Music", sortOrder: 48 },
  { slug: "books", label: "Books & literature", sortOrder: 49 },
  { slug: "photography", label: "Photography", sortOrder: 50 },
  { slug: "art-design", label: "Art & design", sortOrder: 51 },
  { slug: "automotive", label: "Automotive", sortOrder: 52 },
  { slug: "news", label: "News & media", sortOrder: 53 },
  { slug: "business", label: "Business", sortOrder: 54 },
  { slug: "ecommerce", label: "E-commerce", sortOrder: 55 },
  { slug: "dropshipping", label: "Dropshipping", sortOrder: 56 },
  { slug: "legal", label: "Legal", sortOrder: 57 },
  { slug: "environment", label: "Environment & sustainability", sortOrder: 58 },
  { slug: "wedding", label: "Wedding", sortOrder: 59 },
  { slug: "celebrity", label: "Celebrity & gossip", sortOrder: 60 },
];
