export const SEED_LANGUAGES: { code: string; name: string; sortOrder: number }[] = [
  { code: "en", name: "English", sortOrder: 1 },
  { code: "ur", name: "Urdu", sortOrder: 2 },
  { code: "hi", name: "Hindi", sortOrder: 3 },
  { code: "ar", name: "Arabic", sortOrder: 4 },
  { code: "zh", name: "Chinese (Mandarin)", sortOrder: 5 },
  { code: "es", name: "Spanish", sortOrder: 6 },
  { code: "fr", name: "French", sortOrder: 7 },
  { code: "de", name: "German", sortOrder: 8 },
  { code: "it", name: "Italian", sortOrder: 9 },
  { code: "pt", name: "Portuguese", sortOrder: 10 },
  { code: "ru", name: "Russian", sortOrder: 11 },
  { code: "ja", name: "Japanese", sortOrder: 12 },
  { code: "ko", name: "Korean", sortOrder: 13 },
  { code: "tr", name: "Turkish", sortOrder: 14 },
  { code: "nl", name: "Dutch", sortOrder: 15 },
  { code: "pl", name: "Polish", sortOrder: 16 },
  { code: "sv", name: "Swedish", sortOrder: 17 },
  { code: "da", name: "Danish", sortOrder: 18 },
  { code: "no", name: "Norwegian", sortOrder: 19 },
  { code: "fi", name: "Finnish", sortOrder: 20 },
  { code: "el", name: "Greek", sortOrder: 21 },
  { code: "he", name: "Hebrew", sortOrder: 22 },
  { code: "th", name: "Thai", sortOrder: 23 },
  { code: "vi", name: "Vietnamese", sortOrder: 24 },
  { code: "id", name: "Indonesian", sortOrder: 25 },
  { code: "ms", name: "Malay", sortOrder: 26 },
  { code: "bn", name: "Bengali", sortOrder: 27 },
  { code: "ta", name: "Tamil", sortOrder: 28 },
  { code: "te", name: "Telugu", sortOrder: 29 },
  { code: "fa", name: "Persian", sortOrder: 30 },
];
