/** ISO-style country list for reference data (name + code). */
export const SEED_COUNTRIES: { code: string; name: string; sortOrder: number }[] = [
  { code: "US", name: "United States", sortOrder: 1 },
  { code: "GB", name: "United Kingdom", sortOrder: 2 },
  { code: "CA", name: "Canada", sortOrder: 3 },
  { code: "AU", name: "Australia", sortOrder: 4 },
  { code: "DE", name: "Germany", sortOrder: 5 },
  { code: "FR", name: "France", sortOrder: 6 },
  { code: "IT", name: "Italy", sortOrder: 7 },
  { code: "ES", name: "Spain", sortOrder: 8 },
  { code: "NL", name: "Netherlands", sortOrder: 9 },
  { code: "BE", name: "Belgium", sortOrder: 10 },
  { code: "CH", name: "Switzerland", sortOrder: 11 },
  { code: "AT", name: "Austria", sortOrder: 12 },
  { code: "SE", name: "Sweden", sortOrder: 13 },
  { code: "NO", name: "Norway", sortOrder: 14 },
  { code: "DK", name: "Denmark", sortOrder: 15 },
  { code: "FI", name: "Finland", sortOrder: 16 },
  { code: "IE", name: "Ireland", sortOrder: 17 },
  { code: "PT", name: "Portugal", sortOrder: 18 },
  { code: "PL", name: "Poland", sortOrder: 19 },
  { code: "CZ", name: "Czech Republic", sortOrder: 20 },
  { code: "GR", name: "Greece", sortOrder: 21 },
  { code: "TR", name: "Turkey", sortOrder: 22 },
  { code: "RU", name: "Russia", sortOrder: 23 },
  { code: "UA", name: "Ukraine", sortOrder: 24 },
  { code: "IN", name: "India", sortOrder: 25 },
  { code: "PK", name: "Pakistan", sortOrder: 26 },
  { code: "BD", name: "Bangladesh", sortOrder: 27 },
  { code: "CN", name: "China", sortOrder: 28 },
  { code: "JP", name: "Japan", sortOrder: 29 },
  { code: "KR", name: "South Korea", sortOrder: 30 },
  { code: "SG", name: "Singapore", sortOrder: 31 },
  { code: "MY", name: "Malaysia", sortOrder: 32 },
  { code: "ID", name: "Indonesia", sortOrder: 33 },
  { code: "PH", name: "Philippines", sortOrder: 34 },
  { code: "TH", name: "Thailand", sortOrder: 35 },
  { code: "VN", name: "Vietnam", sortOrder: 36 },
  { code: "AE", name: "United Arab Emirates", sortOrder: 37 },
  { code: "SA", name: "Saudi Arabia", sortOrder: 38 },
  { code: "IL", name: "Israel", sortOrder: 39 },
  { code: "EG", name: "Egypt", sortOrder: 40 },
  { code: "ZA", name: "South Africa", sortOrder: 41 },
  { code: "NG", name: "Nigeria", sortOrder: 42 },
  { code: "KE", name: "Kenya", sortOrder: 43 },
  { code: "BR", name: "Brazil", sortOrder: 44 },
  { code: "MX", name: "Mexico", sortOrder: 45 },
  { code: "AR", name: "Argentina", sortOrder: 46 },
  { code: "CL", name: "Chile", sortOrder: 47 },
  { code: "CO", name: "Colombia", sortOrder: 48 },
  { code: "NZ", name: "New Zealand", sortOrder: 49 },
  { code: "RO", name: "Romania", sortOrder: 50 },
  { code: "HU", name: "Hungary", sortOrder: 51 },
  { code: "BG", name: "Bulgaria", sortOrder: 52 },
  { code: "HR", name: "Croatia", sortOrder: 53 },
  { code: "RS", name: "Serbia", sortOrder: 54 },
  { code: "SK", name: "Slovakia", sortOrder: 55 },
  { code: "SI", name: "Slovenia", sortOrder: 56 },
  { code: "LT", name: "Lithuania", sortOrder: 57 },
  { code: "LV", name: "Latvia", sortOrder: 58 },
  { code: "EE", name: "Estonia", sortOrder: 59 },
  { code: "LU", name: "Luxembourg", sortOrder: 60 },
];
