export const SEED_LANGUAGES: { code: string; name: string; sortOrder: number }[] = [
  { code: "en", name: "English", sortOrder: 1 },
  { code: "es", name: "Spanish", sortOrder: 2 },
  { code: "fr", name: "French", sortOrder: 3 },
  { code: "de", name: "German", sortOrder: 4 },
  { code: "it", name: "Italian", sortOrder: 5 },
  { code: "pt", name: "Portuguese", sortOrder: 6 },
  { code: "nl", name: "Dutch", sortOrder: 7 },
  { code: "sv", name: "Swedish", sortOrder: 8 },
  { code: "no", name: "Norwegian", sortOrder: 9 },
  { code: "da", name: "Danish", sortOrder: 10 },
  { code: "fi", name: "Finnish", sortOrder: 11 },
  { code: "ja", name: "Japanese", sortOrder: 12 },
  { code: "zh-Hans", name: "Chinese (Simplified)", sortOrder: 13 },
  { code: "zh-Hant", name: "Chinese (Traditional)", sortOrder: 14 },
  { code: "ko", name: "Korean", sortOrder: 15 },
  { code: "ar", name: "Arabic", sortOrder: 16 },
  { code: "tr", name: "Turkish", sortOrder: 17 },
  { code: "he", name: "Hebrew", sortOrder: 18 },
  { code: "fa", name: "Persian (Farsi)", sortOrder: 19 },
  { code: "hi", name: "Hindi", sortOrder: 20 },
  { code: "ur", name: "Urdu", sortOrder: 21 },
  { code: "bn", name: "Bengali", sortOrder: 22 },
  { code: "ta", name: "Tamil", sortOrder: 23 },
  { code: "te", name: "Telugu", sortOrder: 24 },
  { code: "ml", name: "Malayalam", sortOrder: 25 },
  { code: "mr", name: "Marathi", sortOrder: 26 },
  { code: "gu", name: "Gujarati", sortOrder: 27 },
  { code: "pa", name: "Punjabi", sortOrder: 28 },
  { code: "id", name: "Indonesian", sortOrder: 29 },
  { code: "ms", name: "Malay (Bahasa Malaysia)", sortOrder: 30 },
  { code: "th", name: "Thai", sortOrder: 31 },
  { code: "vi", name: "Vietnamese", sortOrder: 32 },
  { code: "tl", name: "Filipino (Tagalog)", sortOrder: 33 },
  { code: "km", name: "Khmer", sortOrder: 34 },
  { code: "my", name: "Burmese", sortOrder: 35 },
  { code: "si", name: "Sinhala", sortOrder: 36 },
  { code: "ne", name: "Nepali", sortOrder: 37 },
  { code: "ru", name: "Russian", sortOrder: 38 },
  { code: "uk", name: "Ukrainian", sortOrder: 39 },
  { code: "pl", name: "Polish", sortOrder: 40 },
  { code: "cs", name: "Czech", sortOrder: 41 },
  { code: "sk", name: "Slovak", sortOrder: 42 },
  { code: "hu", name: "Hungarian", sortOrder: 43 },
  { code: "ro", name: "Romanian", sortOrder: 44 },
  { code: "bg", name: "Bulgarian", sortOrder: 45 },
  { code: "el", name: "Greek", sortOrder: 46 },
  { code: "sw", name: "Swahili", sortOrder: 47 },
  { code: "am", name: "Amharic", sortOrder: 48 },
  { code: "yo", name: "Yoruba", sortOrder: 49 },
  { code: "ha", name: "Hausa", sortOrder: 50 },
  { code: "zu", name: "Zulu", sortOrder: 51 },
];
