export type Enc = "NONE" | "SSL" | "TLS";

export type SmtpProviderPreset = {
  id: string;
  name: string;
  /** When false, SMTP only (no IMAP inbox). */
  includeImap: boolean;
  smtpHost: string;
  smtpPort: number;
  smtpEncryption: Enc;
  imapHost?: string;
  imapPort?: number;
  imapEncryption?: Enc;
  /** Hint under title on form */
  hint?: string;
};

/**
 * Typical SMTP/IMAP defaults — users should confirm with their provider if delivery fails.
 * "Other / Custom" must stay last.
 */
export const SMTP_PROVIDER_PRESETS: SmtpProviderPreset[] = [
  {
    id: "gmail-smtp",
    name: "Gmail",
    includeImap: true,
    smtpHost: "smtp.gmail.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.gmail.com",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Use an App Password if 2FA is on.",
  },
  {
    id: "google-workspace",
    name: "Google Workspace",
    includeImap: true,
    smtpHost: "smtp.gmail.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.gmail.com",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Same endpoints as Gmail; use your @company.com mailbox credentials.",
  },
  {
    id: "outlook-smtp",
    name: "Outlook / Hotmail",
    includeImap: true,
    smtpHost: "smtp-mail.outlook.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "outlook.office365.com",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Personal @outlook.com / @hotmail.com. Microsoft 365 work accounts use the Microsoft 365 preset.",
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    includeImap: true,
    smtpHost: "smtp.office365.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "outlook.office365.com",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Work or school account (@company.onmicrosoft.com or custom domain).",
  },
  {
    id: "yahoo",
    name: "Yahoo Mail",
    includeImap: true,
    smtpHost: "smtp.mail.yahoo.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.mail.yahoo.com",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "icloud",
    name: "iCloud Mail",
    includeImap: true,
    smtpHost: "smtp.mail.me.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.mail.me.com",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Generate an app-specific password in Apple ID settings.",
  },
  {
    id: "aol",
    name: "AOL Mail",
    includeImap: true,
    smtpHost: "smtp.aol.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.aol.com",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "gmx",
    name: "GMX",
    includeImap: true,
    smtpHost: "smtp.gmx.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.gmx.com",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "webde",
    name: "Web.de",
    includeImap: true,
    smtpHost: "smtp.web.de",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.web.de",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "yandex",
    name: "Yandex Mail",
    includeImap: true,
    smtpHost: "smtp.yandex.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.yandex.com",
    imapPort: 993,
    imapEncryption: "SSL",
  },
  {
    id: "mailru",
    name: "Mail.ru",
    includeImap: true,
    smtpHost: "smtp.mail.ru",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.mail.ru",
    imapPort: 993,
    imapEncryption: "SSL",
  },
  {
    id: "mailcom",
    name: "Mail.com",
    includeImap: true,
    smtpHost: "smtp.mail.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.mail.com",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "zoho",
    name: "Zoho Mail",
    includeImap: true,
    smtpHost: "smtp.zoho.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.zoho.com",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "fastmail",
    name: "Fastmail",
    includeImap: true,
    smtpHost: "smtp.fastmail.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.fastmail.com",
    imapPort: 993,
    imapEncryption: "SSL",
  },
  {
    id: "proton",
    name: "Proton Mail",
    includeImap: true,
    smtpHost: "smtp.protonmail.ch",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.protonmail.ch",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "IMAP/SMTP must be enabled for your account (paid plans or Proton Bridge).",
  },
  {
    id: "posteo",
    name: "Posteo",
    includeImap: true,
    smtpHost: "posteo.de",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "posteo.de",
    imapPort: 993,
    imapEncryption: "SSL",
    hint: "Use the hostname Posteo shows in your account (often posteo.de).",
  },
  {
    id: "runbox",
    name: "Runbox",
    includeImap: true,
    smtpHost: "mail.runbox.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "mail.runbox.com",
    imapPort: 993,
    imapEncryption: "SSL",
  },
  {
    id: "mailbox-org",
    name: "Mailbox.org",
    includeImap: true,
    smtpHost: "smtp.mailbox.org",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.mailbox.org",
    imapPort: 993,
    imapEncryption: "SSL",
  },
  {
    id: "ionos",
    name: "IONOS",
    includeImap: true,
    smtpHost: "smtp.ionos.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.ionos.com",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "infomaniak",
    name: "Infomaniak",
    includeImap: true,
    smtpHost: "mail.infomaniak.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "mail.infomaniak.com",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Use the host Infomaniak shows for your domain if different.",
  },
  {
    id: "hostinger",
    name: "Hostinger",
    includeImap: true,
    smtpHost: "smtp.hostinger.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.hostinger.com",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "bluehost",
    name: "Bluehost",
    includeImap: true,
    smtpHost: "smtp.bluehost.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.bluehost.com",
    imapPort: 993,
    imapEncryption: "SSL",
  },
  {
    id: "siteground",
    name: "SiteGround",
    includeImap: true,
    smtpHost: "smtp.siteground.biz",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.siteground.biz",
    imapPort: 993,
    imapEncryption: "SSL",
    hint: "Some accounts use server-specific hostnames from your SiteGround panel.",
  },
  {
    id: "dreamhost",
    name: "DreamHost",
    includeImap: true,
    smtpHost: "smtp.dreamhost.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.dreamhost.com",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "godaddy",
    name: "GoDaddy",
    includeImap: true,
    smtpHost: "smtpout.secureserver.net",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.secureserver.net",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "namecheap",
    name: "Namecheap / Spaceship",
    includeImap: true,
    smtpHost: "mail.privateemail.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "mail.privateemail.com",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Same stack as Private Email; use the hostname from your control panel if different.",
  },
  {
    id: "private-email",
    name: "Private Email",
    includeImap: true,
    smtpHost: "mail.privateemail.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "mail.privateemail.com",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "titan",
    name: "Titan Email",
    includeImap: true,
    smtpHost: "smtp.titan.email",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.titan.email",
    imapPort: 993,
    imapEncryption: "TLS",
  },
  {
    id: "maildoso",
    name: "Maildoso",
    includeImap: true,
    smtpHost: "smtp.maildoso.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "imap.maildoso.com",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "If your host differs, edit the SMTP/IMAP fields below.",
  },
  {
    id: "rackspace",
    name: "Rackspace Email",
    includeImap: true,
    smtpHost: "secure.emailsrvr.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "secure.emailsrvr.com",
    imapPort: 993,
    imapEncryption: "SSL",
  },
  {
    id: "a2hosting",
    name: "A2 Hosting",
    includeImap: true,
    smtpHost: "mail.a2hosting.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "mail.a2hosting.com",
    imapPort: 993,
    imapEncryption: "SSL",
  },
  {
    id: "migadu",
    name: "Migadu",
    includeImap: true,
    smtpHost: "smtp.migadu.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.migadu.com",
    imapPort: 993,
    imapEncryption: "SSL",
  },
  {
    id: "ovh",
    name: "OVHcloud",
    includeImap: true,
    smtpHost: "ssl0.ovh.net",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "ssl0.ovh.net",
    imapPort: 993,
    imapEncryption: "SSL",
    hint: "Some regions use pro?.mail.ovh.net — check your OVH manager.",
  },
  {
    id: "hetzner",
    name: "Hetzner",
    includeImap: true,
    smtpHost: "mail.your-server.de",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "mail.your-server.de",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Replace with the mail host shown in Hetzner Robot / Console for your server.",
  },
  {
    id: "amazon-workmail",
    name: "Amazon WorkMail",
    includeImap: true,
    smtpHost: "smtp.mail.us-east-1.awsapps.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    imapHost: "imap.mail.us-east-1.awsapps.com",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Replace region with your AWS region (e.g. ap-south-1) if different.",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    includeImap: false,
    smtpHost: "smtp.sendgrid.net",
    smtpPort: 587,
    smtpEncryption: "TLS",
    hint: "Send-only. Inbox sync is not available for this provider.",
  },
  {
    id: "amazon-ses",
    name: "Amazon SES",
    includeImap: false,
    smtpHost: "email-smtp.us-east-1.amazonaws.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    hint: "Send-only. Use SMTP credentials from the SES console (region may differ).",
  },
  {
    id: "brevo",
    name: "Brevo",
    includeImap: false,
    smtpHost: "smtp-relay.brevo.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    hint: "Send-only (formerly Sendinblue).",
  },
  {
    id: "mailjet",
    name: "Mailjet",
    includeImap: false,
    smtpHost: "in-v3.mailjet.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    hint: "Send-only.",
  },
  {
    id: "mailgun",
    name: "Mailgun",
    includeImap: false,
    smtpHost: "smtp.mailgun.org",
    smtpPort: 587,
    smtpEncryption: "TLS",
    hint: "Send-only. Use SMTP credentials from your Mailgun domain.",
  },
  {
    id: "postmark",
    name: "Postmark",
    includeImap: false,
    smtpHost: "smtp.postmarkapp.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    hint: "Send-only.",
  },
  {
    id: "mandrill",
    name: "Mandrill",
    includeImap: false,
    smtpHost: "smtp.mandrillapp.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    hint: "Send-only (Mailchimp transactional).",
  },
  {
    id: "elastic-email",
    name: "Elastic Email",
    includeImap: false,
    smtpHost: "smtp.elasticemail.com",
    smtpPort: 2525,
    smtpEncryption: "TLS",
    hint: "Send-only.",
  },
  {
    id: "resend",
    name: "Resend",
    includeImap: false,
    smtpHost: "smtp.resend.com",
    smtpPort: 465,
    smtpEncryption: "SSL",
    hint: "Send-only.",
  },
  {
    id: "sparkpost",
    name: "SparkPost",
    includeImap: false,
    smtpHost: "smtp.sparkpostmail.com",
    smtpPort: 587,
    smtpEncryption: "TLS",
    hint: "Send-only.",
  },
  {
    id: "custom",
    name: "Other / Custom",
    includeImap: true,
    smtpHost: "",
    smtpPort: 587,
    smtpEncryption: "TLS",
    imapHost: "",
    imapPort: 993,
    imapEncryption: "TLS",
    hint: "Enter SMTP and IMAP hostnames from your provider.",
  },
];

export function getSmtpPreset(id: string | null | undefined): SmtpProviderPreset | undefined {
  if (!id) return undefined;
  return SMTP_PROVIDER_PRESETS.find((p) => p.id === id);
}
